blosm:
  addon_zip_path: blender_addon/blosm_2.7.10.zip
  data_dir: blosm_data
  join_tiles_objects: false
  lod: lod4
  relative_to_initial_import: true
  scale_factor: 0.1
  threed_tiles_source: google
input:
  max_lat:
  max_lon:
  min_lat:
  min_lon:
output:
  base_name:
  output_dir: ./output
secret:
  google_api_key:
