# Currently, release for the installer is only on Windows
name: Release Installer

on:
  push:
    branches:
      - main
    paths:
      - install/windows/installer.bat

permissions:
  contents: write

jobs:
  create-release:
    name: Create Release and Upload Installer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Find out next version
        id: version
        run: |
          latest_release=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r '.tag_name')
          if [[ "$latest_release" == "null" ]]; then
            echo "RELEASE_VERSION=v1.0.0" >> $GITHUB_ENV
          else
            base_version=${latest_release%.*}
            next_patch=$(( ${latest_release##*.} + 1 ))
            echo "RELEASE_VERSION=${base_version}.${next_patch}" >> $GITHUB_ENV
          fi

      - name: Create GitHub Release and Upload
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          files: install/windows/installer.bat
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
